name: open_meteo_api
description: A Dart Api Client for the Open-Meteo API.
version: 0.0.1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  http: ^0.13.5
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  mocktail: ^0.3.0
  test: ^1.22.2
  very_good_analysis: ^3.1.0
